.github/workflows/codeql.yml
enable default configuration for CodeQL Analysis by GitHub
=> MNU-125: codeql.yml

.gitignore, backend/pyproject.toml, backend/src/tenis_backend/app.py, backend/src/tenis_backend/auth.py
MNU-120: adding websocket support via flask-sock
=> MNU-120: adding websocket support via flask-sock

backend/src/tenis_backend/alert.py, backend/src/tenis_backend/app.py, input_plugins/file/tenis_input_file.py
- Implement proper 'resolve' event
- Update resolve protocol for input plugins: only 'project', 'host' and 'alertName' are accepted for resolving now
=> - Implement internal deduplication with global in-mem alerts list

input_plugins/Nagios/README.txt, input_plugins/Nagios/install.sh, input_plugins/Nagios/tenis_nip.py
TT-156: Nagios input plugin for TENIS
=> TT-156: Nagios input plugin for TENIS

backend/src/tenis_backend/alert.py, backend/src/tenis_backend/app.py, input_plugins/Nagios/README.txt, input_plugins/Nagios/install.sh, input_plugins/Nagios/tenis_nip.py
TT-163: nagios plugin update, back update, check if msg or severity changed
=> TT-163: nagios plugin update, back update

backend/src/tenis_backend/app.py, input_plugins/Nagios/tenis_nip.py
TT-163: updated alerts needs to be sent to clients
=> TT-163: updated alerts needs to be sent to clients

backend/src/tenis_backend/app.py, input_plugins/Nagios/tenis_nip.py
=> TT-163: a bit of polishing

backend/README.md, backend/pyproject.toml, backend/src/tenis_backend/__main__.py, backend/src/tenis_backend/alert.py, backend/src/tenis_backend/app.py
=> Implement history

input_plugins/Nagios/README.txt, input_plugins/Nagios/install.sh, input_plugins/Nagios/tenis_nip.py
TT-167: added status.dat parser to renew statuses of all Nagios' services in Tenis upon plugin (re)start. Added Nagios' config file parser to make NIP able to get all needed paths/configs by itself. Changed readme accordingly. Refactored code a bit.
=> TT-167: added status.dat parser for NIP

input_plugins/Nagios/tenis_nip.py
TT-167: rename isScheduled to silenced, grep only alerts from status.dat
=> TT-167: rename isScheduled to silenced, grep only alerts from status.dat

backend/src/tenis_backend/app.py
TT-176: remove 'delete' method as discussed on call
=> TT-176: remove 'delete' method as discussed on call

backend/install.sh
quick fix for install procedure
=> fix install.sh for macos

backend/src/tenis_backend/app.py
TT-185: added 'ack' and 'unack' methods
=> TT-185: added 'ack' and 'unack' methods

backend/src/tenis_backend/app.py
TT-185: update /ack endpoint and add /silence endpoint
=> TT-185: update /ack endpoint and add /silence endpoint

backend/src/tenis_backend/app.py
TT-185: add /silenced endpoint
=> TT-185: add /silenced endpoint

backend/src/tenis_backend/app.py
=> TT-185: /ack update

backend/src/tenis_backend/app.py
=> TT-185: silence_schema update

backend/src/tenis_backend/alert.py, backend/src/tenis_backend/app.py
TT-186: update /silence method
=> TT-186: update /silence method

backend/src/tenis_backend/alert.py, backend/src/tenis_backend/app.py
TT-186: add /unsilence endpoint
=> TT-186: add /unsilence endpoint

backend/src/tenis_backend/app.py
=> TT-186: remove test 'print'

backend/src/tenis_backend/alert.py, backend/src/tenis_backend/app.py
TT-186: checking new alerts(updates) against existing silencing rules
=> TT-186: checking new alerts(updates) against existing silencing rules

backend/src/tenis_backend/app.py
TT-186: fix imports after merge
=> TT-186: fix imports after merge

backend/src/tenis_backend/app.py
=> TT-186: silencing in memory

backend/src/tenis_backend/app.py
=> TT-186: fix unsilencing

backend/src/tenis_backend/app.py
TT-186: cosmetic fix for /silenced, removed redundant code
=> TT-186: cosmetic fix for /silenced, removed redundant code

backend/src/tenis_backend/app.py, backend/src/tenis_backend/json_validation.py, backend/src/tenis_backend/user.py
TT-190: remove passwords from /user* output, add user* json validation, move json schemas to a separate file for better readability
TT-190: /user/update is a bit differ, created separate schema for it
=> TT-190: remove passwords output, add json validations

input_plugins/nagios/tenis_nip.py
=> TT-194: small fix and update

backend/src/tenis_backend/app.py, backend/src/tenis_backend/auth.py, backend/src/tenis_backend/json_validation.py, input_plugins/nagios/install.sh, input_plugins/nagios/tenis_nip.py
TT-194: alerts check added to NIP
=> TT-194: alerts check added to NIP

input_plugins/nagios/tenis_nip.py
=> TT-194: fixing alerts check

backend/src/tenis_backend/app.py, backend/src/tenis_backend/json_validation.py, input_plugins/nagios/tenis_nip.py
=> TT-200: add commands for NIP

frontend/src/components/Alert/Alert.jsx, frontend/src/components/MainPage/MainPage.module.css
change sidebar arrow direction & added hint to ack button
=> TT-198 [front] Prepare UI to use Tenis in prod 

frontend/src/components/MainPage/MainPage.jsx
fix search param while refresh token
=> TT-198 [front] Prepare UI to use Tenis in prod

backend/src/tenis_backend/app.py, input_plugins/nagios/tenis_nip.py
TT-200: add msg comparison/update in NIP alert check
=> TT-200: add msg comparison/update in NIP alert check

frontend/src/components/FilterMenu/FilterMenu.jsx
Added hints for save preferences tumbler
=> TT-177 [front] Implement user preferences

backend/src/tenis_backend/json_validation.py
TT-200: bump maxitems in command_schema
=> TT-200: bump maxitems in command_schema

input_plugins/nagios/tenis_nip.py
TT-200: looks like Nagios' command file must be opened in 'w' mode
=> TT-200: looks like Nagios' command file must be opened in 'w' mode

backend/src/tenis_backend/app.py, input_plugins/nagios/tenis_nip.py
TT-200: add commands recheck_all,recheck_host,recheck_alert
=> TT-200: add commands recheck_all,recheck_host,recheck_alert

frontend/src/components/AlertGroup/AlertGroup.jsx, frontend/src/components/Header/Header.jsx
[rework according to new schema rules]
=> TT-202 [front] Enable force recheck [rework according to new schema

backend/src/tenis_backend/app.py
TT-207: removing redundant try...except
=> TT-207: removing redundant try...except

backend/src/tenis_backend/alert.py
TT-207: add 'plugin_id' check to lookup_alert and update_alerts
=> TT-207: add 'plugin_id' check to lookup_alert and update_alerts

backend/src/tenis_backend/app.py
TT-207: add tmp /out of all alerts without plugin_id prompt
=> TT-207: add tmp /out of all alerts without plugin_id prompt

backend/src/tenis_backend/app.py, backend/src/tenis_backend/json_validation.py, input_plugins/nagios/tenis_nip.py
TT-207: add 'plugin_id' field to resolves
=> TT-207: add 'plugin_id' field to resolves

backend/src/tenis_backend/user.py
the password will now be stored as a hash from the user/update endpoint
=> TT-214 password updates insert plain data in DB

backend/src/tenis_backend/alert.py, backend/src/tenis_backend/app.py, backend/src/tenis_backend/json_validation.py
TT-207: add /comment method to add/change alert's comments
=> TT-207: add /comment method to add/change alert's comments

input_plugins/nagios/tenis_nip.py
NIP logging update, log tenis response code if it's 400 or higher
=> NIP logging update, log tenis response code if it's not ok

backend/src/tenis_backend/app.py
TT-236: add history update for /comment
=> TT-236: add history update for /comment

backend/pyproject.toml, backend/src/tenis_backend/alert.py, backend/src/tenis_backend/app.py, backend/src/tenis_backend/escalation.py
BR-24578: add escalation call via Twilio
=> BR-24578: add escalation call via Twilio
